### ISSUE TITLE
Failed to restore the Lync Status

### ISSUE THREAD

**Issue by shuaibsarkar** [nwinkler/sleepwatcher-lync-status#1]
Hi,

I have installed this and this is working fine, when I lock my computer it sets the status to away but when I unlock the machine it doesn't restore the status.

I lock my mac OS X 10.9.5 with the following key combination Ctrl+Shift+Power (As my keyboard does not have a Eject button)

Regards,
Shuaib

**Comment by nwinkler** [comment]
Can you check the `/var/log/system.log` file for any messages like the following, after locking your screen and then unlocking it again:

```
Jan 30 08:17:43 name com.nilswinkler.sleepwatcher-lync-status[33293]: Lync Status: Appear Away
Jan 30 08:17:54 name com.nilswinkler.sleepwatcher-lync-status[33306]: Lync Status: Busy
```

The daemon and the scripts are supposed to write messages like the above to the `system.log` file when storing and restoring the status.

**Comment by nwinkler** [comment]
You can do a `sudo tail -f /var/log/system.log | grep "sleepwatcher"` to check the log file, or use the _Console_ application (which you may have to start with admin rights in order to get access to this file).

**Comment by shuaibsarkar** [comment]
This is what I got:

Feb  2 14:52:38 shuaibs-Mac-mini-17.local com.nilswinkler.sleepwatcher-lync-status[32778]: Lync Status: Appear Away
Feb  2 14:52:42 shuaibs-Mac-mini-17.local com.nilswinkler.sleepwatcher-lync-status[32791]: Lync Status: Available

Actually this is working fine after performing following steps:

1 - Restart System
2 - Sign in to Lync
3 - Lock the screen (Then it sets the status Away)
4 - Unlock the screen and reset the Lync status by clicking (Reset Status)

After these steps the script seems to working perfect. Thanks a lot for all your help and for the script.
Cheers !!

**Comment by nwinkler** [comment]
Good to hear - thanks!
